spring:
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/xht-cloud-generate?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_uuid
      logic-delete-field: delFlag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    banner: false
  mapper-locations: classpath*:/mapper/**/*.xml  #加载mybatis的配置文件


# swagger的文档配置
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
  default-flat-param-object: true