server:
  port: 8081
spring:
  application:
    name: xht-cloud-demo
  data:
    redis:
      sentinel:
        master: master
        nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381
  datasource:
    url: jdbc:p6spy:mysql://192.168.100.1:3306/xht-cloud?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  profiles:
    active: @profiles.active@
xht:
  cloud:
    web:
      signature:
        enabled: true
        type: database

knife4j:
  enable: true
  setting:
    enable-open-api: false
  basic:
    enable: true
    username: admin
    password: admin
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_uuid
      logic-delete-field: delFlag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 0)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 1)
    banner: false