server:
  port: 8081
spring:
  application:
    name: xht-cloud-demo
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: 123456
    virtual-host: /
    publisher-confirm-type: NONE #确认消息已发送到交换机(Exchange)
    publisher-returns: true #确认消息已发送到队列(Queue)
    connection-timeout: 1s  # 设置MQ的连接超时时间
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1 # 设置每次最多从消息队列服务器取回多少消息
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000ms # 初识的失败等待时长为1秒
          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 10 # 最大重试次数
          stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false
    template:
      mandatory: true # 定义消息路由失败时的策略。true，则调用ReturnCallback；false：则直接丢弃消息
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
        max-attempts: 5 # 最大重试次数


  data:
    redis:
      sentinel:
        master: master
        nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381
  datasource:
    url: jdbc:p6spy:mysql://192.168.100.1:3306/xht-cloud?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  profiles:
    active: @profiles.active@
xht:
  cloud:
    web:
      signature:
        enabled: true
        type: database

knife4j:
  enable: true
  setting:
    enable-open-api: false
  basic:
    enable: true
    username: admin
    password: admin
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_uuid
      logic-delete-field: delFlag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 0)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 1)
    banner: false