server:
  port: 7030
spring:
  application:
    name: xht-cloud-mall-service
  profiles:
    active: @profiles.active@
  datasource:
    url: jdbc:p6spy:mysql://192.168.100.1:3306/xht-cloud-mall?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
knife4j:
  enable: true
  setting:
    enable-open-api: false
springdoc:
  default-flat-param-object: true

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_uuid
      logic-delete-field: delFlag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    banner: false