spring:
  datasource:
    url: jdbc:p6spy:mysql://192.168.100.1:3306/xht-cloud?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_uuid
      logic-delete-field: delFlag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 0)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 1)
    banner: false
  mapper-locations: classpath*:/mapper/**/*.xml  #加载mybatis的配置文件
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
xht:
  cloud:
    oss:
      bucket-name: test3
      host: http://127.0.0.1:8001
      access-key: TdHpEqJaiW2nsx8eUHLf
      secret-key: f0YdJM85vJ85vFuE0fArKJStBl45GEQ5AnjsL6dI
      part:
        enabled: true